config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  # 測試用
  # devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  
  # 正式用
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations" }
  # devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "/users", to: "users/registrations#new"
    get "/users/password", to: "users/passwords#new"
    get "/user_dashboard/settings", to: "users/registrations#edit", as: "user_dashboard"
  end

  namespace :users, path: :u do
    get "/:username", to: "profiles#show", as: "profile"
    post "/:username", to: "profiles#follow", as: "follow"
    get "/:username/wishlist", to: "profiles#wishlist", as: "wishlist"
    post "/:username/wishcart", to: "profiles#wishcart"
    delete "/:username/unwish", to: "profiles#unwish", as: "unwish"
  end
  
  namespace :users, path: :dash_board do
    get "/followship", to: "profiles#followship"
    get "/books", to: "authors#show"
    get "/library", to: "library#show"
    post "/library", to: "library#comment", as: "comment"
  end

  resources :books do
    member do
      get :editor_new
      post :editor_create
      get :editor_edit
      post :editor_update
      get :pricing
      patch :publish
      post :add_chapter
      post :add_section
      get :sample
      get :table_of_contents
      get :read
      patch :unpublish
      post :wish
    end
    
    collection do
      get :search
      post :get_content
      post :update_content
      post :rename
      post :delete_chapter_or_section
      post :all_content
      post :upload_pdf
      post :download_pdf
    end
  end

  get "/purchases", to: "users/purchase#index"
  get "/purchases_show", to: "users/purchase#show"

  resource :cart, only:[:show, :edit, :update, :destroy] do
    collection do
      post :add, path:'add/:id'
      get :payment
      post :checkout
      post :refund
      post :cartwish
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/frontend/_book_cover.html.erb
<% if book.cover_data %>
  <%= image_tag book.cover_url(size), class: "book-cover cover-img w-100 " %>
<% else %>
  <%= image_pack_tag "open_book_cover.jpeg", class: "book-cover cover-img w-100" %>
<% end %>

app/views/shared/frontend/_cart_modal.html.erb
<div class="cart-modal x" data-controller="modal" data-target="modal.body">
  <div class="modal-content">
    <div class="col-lg-6 mx-auto">
      <div class="modal-header">
        <h3 class="modal-title">Edit Purchase</h3>
        <button type="button" class="close" data-dismiss="modal" data-action="modal#close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-body">
        <div class="row">
          <!-- 書本封面 -->
          <div class="col-4">
            <div class="modal-body-img"></div>
            <div class="modal-body-title"></div>
            <div class="modal-body-author"></div>
          </div>
  
          <div class="col-8">
            <!-- Slider -->
            <!-- 最大最小價格 -->
            <div class="d-flex book-price">
              <div class="mr-3">
                <p class="modal-min text-center mb-0"></p>
                <p>MINIMUM PRICE</p>
              </div>
              <div>
                <p class="modal-max text-center mb-0"></p>
                <p>SUGGESTED PRICE</p>
              </div>
            </div>
  
            <!-- Slider -->
            <div class="slider mb-4">
              <p class="mb-1">YOU PAY</p>
              <div class="user-pay d-flex">
                <div class="user-pay-box">
                  <span class="modal-user-pay-show">$</span>
                </div>
                <input id="modal-user-pay" class="w-100 mb-3" type="range" step="0.01">
              </div>
  
              <p class="mb-1">AUTHOR EARNS</p>
              <div class="author-earns d-flex">
                <div class="author-earns-box">
                  <span class="modal-author-earns-show">$</span>
                </div>
                <input id="moadl-author-earns" class="w-100" type="range" step="0.01">
              </div>
            </div>
  
            <!-- 更新價格按鈕 -->
            <div class="update-price mt-auto">
              <span>YOU PAY</span>
              <span class="hint">(US$)</span>
              <%= form_with url: cart_path, method: :patch, class: "update-price-form", data: {action: "modal#update", target: "modal.update_form"} do |f| %>
                <%= f.text_field :cart_price, id: "modal-cart-price", class: "modal-cart-price text-center d-block mt-1 mb-4", data: {target: "modal.price"} %>
                <%= f.submit "Update", class: "update-btn btn btn-danger main-btn", data: {target: "modal.update_btn"} %>
                <button class="cart-wait-btn btn btn-danger main-btn x" disabled data-target="modal.cart_wait">Please wait...</button>
              <% end %>
            </div>

            <!-- 加入購物車按鈕 -->
            <div class="add-to-cart-price mt-auto">
              <span>YOU PAY</span>
              <span class="hint">(US$)</span>
              <%= form_with url: "#", class: "add-cart-form-modal" do |f| %>
                <%= f.text_field :cart_price, id: "cart-price-modal", class: "cart-price text-center mt-1 mb-4" %>
                <div>
                  <%= f.submit "Add Ebook to Cart", id: "wish-to-cart", class: "add-to-cart-btn btn btn-danger main-btn" %>
                </div>
                <button class="wish-wait-btn btn btn-danger main-btn x" disabled>Please wait...</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/frontend/_footer.html.erb
<footer class="footer py-2 w-100 bg-dark">
	<div class="container col-md-12 col-lg-6">
    <div class="row align-items-center justify-content-center text-center">
      <span>Copyright © 2020 Simpub Corp. <br>All rights reserved.</span>
    </div>
	</div>
</footer>

app/views/shared/frontend/_navbar.html.erb
<nav class="layout-navbar navbar navbar-expand-lg navbar-dark bg-dark d-flex sticky-top" data-controller="notify">
  <!-- 品牌 logo -->
  <div class="logo col-1">
    <a href="/" class="navbar-brand">  
      <%= image_pack_tag "logo.png", class: "logo-desktop img-fluid" %>
    </a>
  </div>
  
  <button class="navbar-toggler" type="button" data-trigger="#main_nav">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- 收合選單開始 -->
  <div class="navbar-collapse bg-dark" id="main_nav">
    <div class="offcanvas-header">
      <button class="btn btn-outline-danger btn-close float-right">
        &times
      </button>
    </div>

    <!-- 導覽列選單 -->
    <ul class="nav-item-group navbar-nav">
      <li class="nav-item">
        <%= link_to "Books", books_path, class: "nav-link txt" %>
      </li>
      <%# 有登入才是以下內容 %>
      
      <li class="nav-item"><%= link_to "Library", users_library_path, class: "nav-link txt" %></li>
      <li class="nav-item">
        <%= link_to "Create a Book", new_book_path, class: "nav-link txt" %>      
      </li>
        <%# 是作者才顯示寫了哪些書 %>
        <%# <% if current_user.as_author %> 
          <li class="nav-item">
            <%= link_to "My Writings", users_books_path, class: "nav-link txt" %>
          </li>
    </ul>

    <!-- Search Filter -->
    <div class="search-filter" data-controller="search">
      <select name="" id="search-selector" class="btn" data-target="search.select" style="color: white">
        <option value="book-search">Book Title</option>
        <option value="author-search">Book Author</option>
        <option value="tag-search">Book Tags</option>
      </select>
      <div class="row search-bar">
        <!-- book search 表單 -->
        <%= form_with url: books_path, method: :get, class: "nav-search x form-inline d-flex flex-nowrap ml-4", local: true, data: {target: "search.book_search"} do |f| %>
          <%= f.search_field :book_search, class: "search-input book-search-input form-control", placeholder: "Search" %>
          <%= f.button :submit, class: "search-btn btn btn-outline-black" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>

        <!-- author search 表單 -->
        <%= form_with url: books_path, method: :get, class: "nav-search author-search x form-inline d-flex flex-nowrap ml-4", local: true, data: {target: "search.author_search"} do |f| %>
          <%= f.search_field :author_search, class: "search-input author-search-input form-control", placeholder: "Search" %>
          <%= f.button :submit, class: "search-btn btn btn-outline-black" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>

        <!-- tag search 表單 -->
        <%= form_with url: books_path, method: :get, class: "nav-search tag-search x form-inline d-flex flex-nowrap ml-4", local: true, data: {target: "search.tag_search"} do |f| %>
          <%= f.search_field :tag_search, class: "search-input tag-search-input form-control", placeholder: "Search" %>
          <%= f.button :submit, class: "search-btn btn btn-outline-black" do %>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>
      </div>
		</div>

    <!-- 購物車、願望清單、通知 -->
    <div class="icon-group-desktop">
      <!-- 開燈/關燈 -->
      <div class="icon-btn">
        <i class="light-icon mx-2 fas fa-moon"></i>
      </div>
      
      <input id="switch" type="checkbox" name="theme">
      <label for="switch" hidden></label>

      <!-- 購物車 -->
      <%= link_to cart_path, class:"nav-icon" do %>
        <i class="fas fa-shopping-cart mx-2">
          <div class="x"></div>
        </i>
      <% end %>
      
      <!-- 願望清單 -->
      <% if user_signed_in? %>
      <div class="nav-icon" data-controller="wish" data-wish-username="<%= current_user.username %>">
        <%= link_to users_wishlist_path(current_user.username), class: "nav-icon" do %>
          <i class="fas fa-heart mx-2">
            <div class="x" data-target="wish.bubble"></div>
          </i>
        <% end %>
      </div>

      <!-- 通知 -->
      <div class="nav-icon">
        <button class="nav-icon border-0 bg-transparent p-0" data-action="notify#show">
          <i class="fas fa-bell mx-2">
            <div class="x" data-target="notify.bubble"></div>
          </i>
        </button>
      </div>
      <% end %>
    </div>

    <!-- 使用者選單 -->
    <ul class="navbar-nav user-menu">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
            User Menu
          </a>
          <ul class="dropdown-menu dropdown-menu-right">
            <!-- 個人主頁 -->
            <li class="dropdown-item">
              <%= link_to "View Profile", users_profile_path(current_user.username), class:"nav-drop-item" %>
            </li>

            <!-- 編輯個人主頁 -->
            <li class="dropdown-item">
              <%= link_to "Edit Profile", user_dashboard_path, class:"nav-drop-item" %>
            </li>

            <!-- 追隨 -->
            <li class="dropdown-item">
              <%= link_to "Follows", users_followship_path, class: "nav-drop-item" %>
            </li>

            <!-- 購買紀錄 -->
            <li class="dropdown-item">
              <a href="/purchases" class="nav-drop-item">Purchases</a>
            </li>
            
            <%# 願望清單連結 %>
            <li class="dropdown-item">
              <%= link_to 'Wish List',users_wishlist_path(current_user.username),class: "nav-drop-item" %>
            </li>

            <!-- 登出 -->
            <li class="dropdown-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign_out_btn nav-drop-item"%>
            </li>
          </ul>
        </li>
      <% else %>

        <!-- 註冊 -->
        <%= link_to "Sign Up", new_user_registration_path, class: "sing_up nav-link" %>
        
        <!-- 登入 -->
        <%= link_to "Sign In", new_user_session_path, class: "sing_in nav-link" %>
      <% end %>
    </div>
  </div>
  <!-- 收合選單結束 -->

  <!-- 購物車、願望清單、通知 -->
  <div class="icon-group-mobile">
    <!-- 開燈/關燈 -->
    <div class="icon-btn">
      <i class="light-icon mx-2 fas fa-moon"></i>
    </div>

    <!-- 購物車 -->
    <%= link_to cart_path, class:"nav-icon" do %>
      <i class="fas fa-shopping-cart mx-2">
        <div class="x"></div>
      </i>
    <% end %>
    
    <!-- 願望清單 -->
    <% if user_signed_in? %>
    <div class="nav-icon" data-controller="wish" data-wish-username="<%= current_user.username %>">
      <%= link_to users_wishlist_path(current_user.username), class: "nav-icon" do %>
        <i class="fas fa-heart mx-2">
          <div class="x" data-target="wish.bubble"></div>
        </i>
      <% end %>
    </div>

    <!-- 通知 -->
    <div class="nav-icon">
      <button class="nav-icon border-0 bg-transparent p-0" data-action="notify#show">
        <i class="fas fa-bell mx-2">
          <div class="x" data-target="notify.bubble"></div>
        </i>
      </button>
    </div>
    <% end %>
  </div>

  <div id="notify-box" class="position-fixed x">
    <div class="d-flex px-3 py-2 border-bottom justify-content-between">
      <div class="title">Notifications</div>
      <div class="clear-notify" data-action="click->notify#mark_read">Clear All</div>
    </div>
    <div class="notify-content" data-target="notify.box"></div>
  </div>
</nav>

app/views/shared/frontend/_price_slider.html.erb
<!-- 最大最小價格 -->
<div class="d-flex book-price">
  <div class="mr-5">
    <h2 class="mb-0">$<%= book.price %></h2>
    <p>MINIMUM PRICE</p>
  </div>
  <div>
    <h2 class="mb-0">$<%= book.price * 2 %></h2>
    <p>SUGGESTED PRICE</p>
  </div>
</div>

<!-- Slider -->
<div class="slider mb-4">
  <h5 class="mb-1">You Paid</h5>
  <div class="user-pay d-flex my-2">
    <div class="user-pay-box rounded-left">
      <span class="user-pay-show">$<%= book.price * 2 %></span>
    </div>
    <input id="user-pay" class="w-100 rounded-right mb-3" type="range" min="<%= book.price %>" max="<%= book.price * 3 %>" value="<%= book.price * 2 %>" step="0.01">
  </div>

  <h6 class="mb-1">Author Earns</h6>
  <div class="author-earns d-flex my-2">
    <div class="author-earns-box rounded-left">
      <span class="author-earns-show">$<%= book.price * 2 * 0.8 %></span>
    </div>
    <input id="author-earns" class="w-100 rounded-right" type="range" min="<%= book.price * 0.8 %>" max="<%= book.price * 4 %>" value="<%= book.price * 2 %>" step="0.01">
  </div>
</div>

app/views/shared/frontend/_user_avatar.html.erb
<% if has_avatar?(user) %>
  <%= image_tag user.avatar_url(:small), class: "w-100 rounded-circle" %>
<% else %>
  <%= image_pack_tag "dummy_avatar.png", class: "w-100" %>
<% end %>