config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  # 測試用
  # devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  
  # 正式用
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations" }
  # devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "/users", to: "users/registrations#new"
    get "/users/password", to: "users/passwords#new"
    get "/user_dashboard/settings", to: "users/registrations#edit", as: "user_dashboard"
  end

  namespace :users, path: :u do
    get "/:username", to: "profiles#show", as: "profile"
    post "/:username", to: "profiles#follow", as: "follow"
    get "/:username/wishlist", to: "profiles#wishlist", as: "wishlist"
    post "/:username/wishcart", to: "profiles#wishcart"
    delete "/:username/unwish", to: "profiles#unwish", as: "unwish"
  end
  
  namespace :users, path: :dash_board do
    get "/followship", to: "profiles#followship"
    get "/books", to: "authors#show"
    get "/library", to: "library#show"
    post "/library", to: "library#comment", as: "comment"
  end

  resources :books do
    member do
      get :editor_new
      post :editor_create
      get :editor_edit
      post :editor_update
      get :pricing
      patch :publish
      post :add_chapter
      post :add_section
      get :sample
      get :table_of_contents
      get :read
      patch :unpublish
      post :wish
    end
    
    collection do
      get :search
      post :get_content
      post :update_content
      post :rename
      post :delete_chapter_or_section
      post :all_content
      post :upload_pdf
      post :download_pdf
    end
  end

  get "/purchases", to: "users/purchase#index"
  get "/purchases_show", to: "users/purchase#show"

  resource :cart, only:[:show, :edit, :update, :destroy] do
    collection do
      post :add, path:'add/:id'
      get :payment
      post :checkout
      post :refund
      post :cartwish
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  include AvatarUploader::Attachment(:avatar)

  attr_accessor :x, :y, :width, :height

  # 測試用
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :github]
  
  # 正式用
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable, :confirmable,
  #        :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :github]

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true

  has_many :book_authors
  has_many :pub_books, through: :book_authors, source: :book

  has_many :book_users
  has_many :bought_books, through: :book_users, source: :book

  has_many :orders
  has_many :comments

  has_many :followed_users, foreign_key: :follower_id, class_name: "Followship"
  has_many :followees, through: :followed_users
    
  has_many :following_users, foreign_key: :followee_id, class_name: "Followship"
  has_many :followers, through: :following_users

  has_many :wishlists
  has_many :wish_books, through: :wishlists, source: :book

  has_many :notifications, foreign_key: :recipient_id

  def self.from_omniauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user
      
    if user.nil?
        email = auth.info.email
        user = User.where(email: email).first if email
        if user.nil?
          user = User.new(name: auth.info.name.gsub(/\s+/, '_'),
                          email: auth.info.email,
                          password: Devise.friendly_token[0,20],
                          username: auth.info.name.gsub(/\s+/, '_').downcase)
          user.save!   
        end
      end

      if identity.user != user
        identity.user = user
        identity.save!
      end
      
    user
  end

  def toggle_following(user)
    if following_users.exists?(follower_id: user.id)
      followers.destroy(user)
    else
      followers << user
    end
  end

  def followed_by?(user)
    followees.include?(user)
  end
  
end

app/controllers/users/authors_controller.rb
class Users::AuthorsController < ApplicationController

  def show
    if not user_signed_in?
      redirect_to new_user_session_path, alert: 'You need to sign in or sign up before continuing.'
    else
      if not current_user.as_author
        redirect_to new_book_path, alert: 'Create your books.'
      end
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    root_path
  end
end

app/controllers/users/library_controller.rb
class Users::LibraryController < ApplicationController

  def show
    if user_signed_in?
      @books = current_user.bought_books.includes(:authors)
      @book = Book.find_by(id: params[:bookid])
      @book_info = @book.as_json(include: :authors)
      @comment = current_user.comments.new

      @comments = @book.comments if @book
      @stars = @book.comments.average(:stars).ceil() if @comments and @comments.size > 0

      respond_to do |format|
        format.html
        format.json
        # format.json { render json: @book_info }
      end
      
    else
      redirect_to new_user_session_path, alert: 'You need to sign in or sign up before continuing.'
    end
    
  end
  
  def comment
    @book = current_user.bought_books.find_by(id: params[:id])
    comment = @book.comments.new(comment_params)

    if comment.save
      create_notification(@book.authors[0], current_user, "left a comment on", @book)
      flash[:notice] = "New comment added"
    else
      flash[:notice] = "Something went wrong please try again"
    end

    redirect_to users_library_path
  end


  private
  def comment_params
    params.require(:comment).permit(:stars, :content).merge(user: current_user)
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else

      if @user.email.nil?
        @user.delete_access_token(request.env["omniauth.auth"])
        redirect_to new_user_registration_url, alert: "需要您同意 Email 授權！"
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to "/"
      end
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to "/"
    end
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end


  def failure
    redirect_to new_user_session_path, alert: "無法獲得驗證！"
  end

end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :find_user
  before_action :find_book, only: [:unwish, :wishcart]

  def show
  end

  def follow
    current_user.toggle_following(@user)
    followship = Followship.find_by(follower_id: @user, followee_id: current_user)
    
    # create the notification
    create_notification(@user, current_user, "starts following", followship) if followship
    
    render json: {status: @user.followed_by?(current_user)}
  end

  def followship
    @followers = current_user.followers
    @followees = current_user.followees
  end

  def wishlist
    @books = current_user.wish_books

    respond_to do |format|
      format.html
      format.json { render json: @books.pluck(:slug) }
    end
  end

  def unwish
    remove_wish_book(@book)
    redirect_to users_wishlist_path, notice: "Removed item from your Wish List"
  end

  def wishcart
    remove_wish_book(@book)
  end
  
  private
  def find_user
    @user = User.find_by(username: params[:username])
  end

  def find_book
    @book = Book.friendly.find(params[:id])
  end

  def remove_wish_book(book)
    current_user.wish_books.destroy(book)
  end
end

app/controllers/users/purchase_controller.rb
class Users::PurchaseController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find_by(uuid: params[:uuid])
    @order_items = @order.order_items
    @refund_time = (@order.created_at.next_day(45).to_date - @order.created_at.to_date).to_i
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create, :update]

  def new
    @users = User.all

    respond_to do |format|
      format.html { super }
      format.json { @users }
    end
  end

  def update
    super

    if params[:user][:x].present?
      AvatarUploaderJob.perform_later(current_user, crop: { x: params[:user][:x], y: params[:user][:y], w: params[:user][:width], h: params[:user][:height] })
    end
  end
 
  private
  # 在 devise 中加入 name & username 欄位
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name, :username, :about, :password, :facebook, :github, :x, :y, :width, :height])
  end

  # update 的時候不需要驗證密碼
  def update_resource(resource, params)
    new_params = params
    new_params[:password] = nil if new_params[:password] == ""
    resource.update(new_params)
  end
end

app/views/users/profiles/followship.html.erb
<section class="followship container" data-controller="followship">
  <h3 class="text-center txt">You are Following</h3>
  <div class="card-box row m-0">
    <% @followers.each do |follower| %>
      <div class="card col-6 col-md-4 col-lg-3 py-3">
        <div class="img-box col-10 col-lg-8 mx-auto">
          <%= render "shared/frontend/user_avatar", user: follower %>
        </div>
        <div class="card-body col-lg-10 text-center">
          <h5 class="card-title"><%= follower.name %></h5>
        </div>
        <button class="follow-btn btn btn-primary txt col-lg-10 w-100" data-username="<%= follower.username %>">
          <% if follower.followed_by?(current_user) %>
            Following
          <% else %>
            Follow
          <% end %>
        </button>
      </div>
    <% end %>
  </div>

  <h3 class="text-center txt mt-5">Who's Following you</h3>
  <div class="card-box row m-0">
    <% @followees.each do |followee| %>
      <div class="card col-6 col-md-4 col-lg-3 py-3">
        <div class="img-box col-10 col-lg-8 mx-auto">
          <%= render "shared/frontend/user_avatar", user: followee %>
        </div>
        <div class="card-body col-lg-10 text-center">
          <h5 class="card-title"><%= followee.name %></h5>
        </div>
        <button class="follow-btn btn btn-primary txt col-lg-10 w-100" data-username="<%= followee.username %>">
          <% if followee.followed_by?(current_user) %>
            Following
          <% else %>
            Follow
          <% end %>
        </button>
      </div>
    <% end %>
  </div>
</section>

app/views/users/profiles/show.html.erb
<section class="profile-show container">
  <div class="row">
    <div class="author-about col-12 d-lg-flex">
      <div class="avatar col-8 col-md-4 col-lg-3">
        <div class="img-box col-12 col-lg-7 mx-auto">
          <%= render "shared/frontend/user_avatar", user: @user %>
        </div>
        <div class="justify-content" data-controller="follow" data-follow-user="<%= @user.username %>">
          <div class="follow col-12 col-lg-10 m-auto">
            <button class="follow-btn btn btn-primary txt w-100", data-action="follow#followship">
              <% if @user.followed_by?(current_user) %>
                Following
              <% else %>
                Follow
              <% end %>
            </button>
          </div>
        </div>
      </div>
      
      <div class="authors-info justify-content col-12 col-md-6 col-lg-9">
        <div class="h3 txt user-name ">
          <%= @user.name %> 
        </div>
        <div class="txt user-about">
          <% if @user.about and @user.about != "" %>
            <%= @user.about %>
          <% else %>
            <p>
              Samuel Miller was born and raised in Vermillion, South Dakota, and now resides in Los Angeles, where, in addition to writing, he directs music videos and coaches Little League Baseball. He began writing his first novel while on tour in a fifteen-passenger van with the rock band Paradise Fears. A Lite Too Bright is his debut novel. Currently he attends graduate school at the University of Southern California. He credits his existence entirely to two spectacular parents, three brothers, one sister, and the best and sweetest puppy dog on the whole planet, Addison.
            </p>
          <% end %>
        </div>
        <div class="txt user-locate d-flex">
          <i class="fas fa-map-marker-alt fa-2x"></i>
          <div class="txt location d-flex">
            <p>Taipei, Taiwan</p>
          </div>
        </div>
        <div class="follow-grop d-flex">
          <div class="txt follow-between d-flex">
            <div class="following">
              <div class="number"><%= rand(100..150) %></div>
              <p>Following</p>
            </div>
            <div class="follower">
              <div class="number"><%= rand(100..150) %></div>
              <p>Follower</p>
            </div>
          </div>

          <div class="contact d-flex ">
            <% if @user.facebook %>
              <%= link_to "https://www.facebook.com/#{@user.facebook}", target: "_blank", class: "facebook" do %>
                <i class="fab fa-facebook fa-3x"></i>
              <% end %>
            <% end %>

            <% if @user.github %>
              <%= link_to "https://github.com/#{@user.github}", target: "_blank", class: "github" do %>
                <i class="fab fa-github fa-3x"></i>
              <% end %>
            <% end %>

            <%= mail_to @user.email , target: "_blank", class: "email" do %>
              <i class="far fa-envelope fa-3x"></i>
            <% end %>
            </a>
          </div>
        </div>
      </div>
    </div>

    <%# 出版過的書 %>
    <div class="row m-0 col-12">
      <h3 class="col-12 title">Published Books</h3>
      <div class="buy-books col-12 row justify-content-between">
        <% @user.pub_books.each do |book| %>
          <div class="book-item col-6 col-lg-2">
            <%= link_to book_path(book) do %>
              <%= render partial: "shared/frontend/book_cover", locals: {book: book, size: :small} %>
              <div class="book-name">
                <h5><%= book.title %></h5>
                <p>
                  <%= book.authors[0].name %>
                </p>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>    
  </div>
</section>

app/views/users/profiles/wishlist.html.erb
<section class="wishlist txt my-4 container">   
  <h1 class="text-center mb-4"><%= current_user.name %>'s Wishlist</h1>   

  <% @books.each do |book| %>
    <div class="row" data-controller="wishlist" data-wishlist-book="<%= book.id %>" data-wishlist-username="<%= current_user.username%>">
      
      <div class="col-12 col-lg-5">
        <div class="cover-box col-6" data-target="wishlist.cover">
          <%= render partial: "shared/frontend/book_cover", locals: {book: book, size: :small} %>
        </div>
      </div>

      <div class="wish-btns col-12 col-lg-7">
        <div class="col-12">
          <p class="book-title"><%= book.title %></p>
        </div>
      
        <div class="wish-btn col-12">
          <button class="item-edit btn btn-primary d-block shadow" data-action="wishlist#cart">Move to cart</button>
          <%= link_to "Remove from your wish list", users_unwish_path(current_user.username, id: book), method: :delete, remote: true, class: "btn btn-outline-secondary d-block" %>
        </div>
      </div>

    </div>

    <div class="d-flex justify-content-center my-3">
        <div class="col-12 col-md-8 border-gray border-bottom"></div>
    </div>     
  <% end %>
</section>