config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  # 測試用
  # devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  
  # 正式用
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations" }
  # devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "/users", to: "users/registrations#new"
    get "/users/password", to: "users/passwords#new"
    get "/user_dashboard/settings", to: "users/registrations#edit", as: "user_dashboard"
  end

  namespace :users, path: :u do
    get "/:username", to: "profiles#show", as: "profile"
    post "/:username", to: "profiles#follow", as: "follow"
    get "/:username/wishlist", to: "profiles#wishlist", as: "wishlist"
    post "/:username/wishcart", to: "profiles#wishcart"
    delete "/:username/unwish", to: "profiles#unwish", as: "unwish"
  end
  
  namespace :users, path: :dash_board do
    get "/followship", to: "profiles#followship"
    get "/books", to: "authors#show"
    get "/library", to: "library#show"
    post "/library", to: "library#comment", as: "comment"
  end

  resources :books do
    member do
      get :editor_new
      post :editor_create
      get :editor_edit
      post :editor_update
      get :pricing
      patch :publish
      post :add_chapter
      post :add_section
      get :sample
      get :table_of_contents
      get :read
      patch :unpublish
      post :wish
    end
    
    collection do
      get :search
      post :get_content
      post :update_content
      post :rename
      post :delete_chapter_or_section
      post :all_content
      post :upload_pdf
      post :download_pdf
    end
  end

  get "/purchases", to: "users/purchase#index"
  get "/purchases_show", to: "users/purchase#show"

  resource :cart, only:[:show, :edit, :update, :destroy] do
    collection do
      post :add, path:'add/:id'
      get :payment
      post :checkout
      post :refund
      post :cartwish
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  include AvatarUploader::Attachment(:avatar)

  attr_accessor :x, :y, :width, :height

  # 測試用
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :github]
  
  # 正式用
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable, :confirmable,
  #        :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :github]

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :username, presence: true, uniqueness: true

  has_many :book_authors
  has_many :pub_books, through: :book_authors, source: :book

  has_many :book_users
  has_many :bought_books, through: :book_users, source: :book

  has_many :orders
  has_many :comments

  has_many :followed_users, foreign_key: :follower_id, class_name: "Followship"
  has_many :followees, through: :followed_users
    
  has_many :following_users, foreign_key: :followee_id, class_name: "Followship"
  has_many :followers, through: :following_users

  has_many :wishlists
  has_many :wish_books, through: :wishlists, source: :book

  has_many :notifications, foreign_key: :recipient_id

  def self.from_omniauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user
      
    if user.nil?
        email = auth.info.email
        user = User.where(email: email).first if email
        if user.nil?
          user = User.new(name: auth.info.name.gsub(/\s+/, '_'),
                          email: auth.info.email,
                          password: Devise.friendly_token[0,20],
                          username: auth.info.name.gsub(/\s+/, '_').downcase)
          user.save!   
        end
      end

      if identity.user != user
        identity.user = user
        identity.save!
      end
      
    user
  end

  def toggle_following(user)
    if following_users.exists?(follower_id: user.id)
      followers.destroy(user)
    else
      followers << user
    end
  end

  def followed_by?(user)
    followees.include?(user)
  end
  
end

app/controllers/users/authors_controller.rb
class Users::AuthorsController < ApplicationController

  def show
    if not user_signed_in?
      redirect_to new_user_session_path, alert: 'You need to sign in or sign up before continuing.'
    else
      if not current_user.as_author
        redirect_to new_book_path, alert: 'Create your books.'
      end
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    root_path
  end
end

app/controllers/users/library_controller.rb
class Users::LibraryController < ApplicationController

  def show
    if user_signed_in?
      @books = current_user.bought_books.includes(:authors)
      @book = Book.find_by(id: params[:bookid])
      @book_info = @book.as_json(include: :authors)
      @comment = current_user.comments.new

      @comments = @book.comments if @book
      @stars = @book.comments.average(:stars).ceil() if @comments and @comments.size > 0

      respond_to do |format|
        format.html
        format.json
        # format.json { render json: @book_info }
      end
      
    else
      redirect_to new_user_session_path, alert: 'You need to sign in or sign up before continuing.'
    end
    
  end
  
  def comment
    @book = current_user.bought_books.find_by(id: params[:id])
    comment = @book.comments.new(comment_params)

    if comment.save
      create_notification(@book.authors[0], current_user, "left a comment on", @book)
      flash[:notice] = "New comment added"
    else
      flash[:notice] = "Something went wrong please try again"
    end

    redirect_to users_library_path
  end


  private
  def comment_params
    params.require(:comment).permit(:stars, :content).merge(user: current_user)
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else

      if @user.email.nil?
        @user.delete_access_token(request.env["omniauth.auth"])
        redirect_to new_user_registration_url, alert: "需要您同意 Email 授權！"
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to "/"
      end
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to "/"
    end
  end

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end


  def failure
    redirect_to new_user_session_path, alert: "無法獲得驗證！"
  end

end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :find_user
  before_action :find_book, only: [:unwish, :wishcart]

  def show
  end

  def follow
    current_user.toggle_following(@user)
    followship = Followship.find_by(follower_id: @user, followee_id: current_user)
    
    # create the notification
    create_notification(@user, current_user, "starts following", followship) if followship
    
    render json: {status: @user.followed_by?(current_user)}
  end

  def followship
    @followers = current_user.followers
    @followees = current_user.followees
  end

  def wishlist
    @books = current_user.wish_books

    respond_to do |format|
      format.html
      format.json { render json: @books.pluck(:slug) }
    end
  end

  def unwish
    remove_wish_book(@book)
    redirect_to users_wishlist_path, notice: "Removed item from your Wish List"
  end

  def wishcart
    remove_wish_book(@book)
  end
  
  private
  def find_user
    @user = User.find_by(username: params[:username])
  end

  def find_book
    @book = Book.friendly.find(params[:id])
  end

  def remove_wish_book(book)
    current_user.wish_books.destroy(book)
  end
end

app/controllers/users/purchase_controller.rb
class Users::PurchaseController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find_by(uuid: params[:uuid])
    @order_items = @order.order_items
    @refund_time = (@order.created_at.next_day(45).to_date - @order.created_at.to_date).to_i
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create, :update]

  def new
    @users = User.all

    respond_to do |format|
      format.html { super }
      format.json { @users }
    end
  end

  def update
    super

    if params[:user][:x].present?
      AvatarUploaderJob.perform_later(current_user, crop: { x: params[:user][:x], y: params[:user][:y], w: params[:user][:width], h: params[:user][:height] })
    end
  end
 
  private
  # 在 devise 中加入 name & username 欄位
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :name, :username, :about, :password, :facebook, :github, :x, :y, :width, :height])
  end

  # update 的時候不需要驗證密碼
  def update_resource(resource, params)
    new_params = params
    new_params[:password] = nil if new_params[:password] == ""
    resource.update(new_params)
  end
end

app/views/users/library/show.html.erb
<div data-controller="library">
  <section class="library container">
    <div class="library-box row align-self-center">
      <div class="user-avatar col-6 col-md-3 col-lg-2 d-flex flex-column">
        <div>
          <%= render "shared/frontend/user_avatar", user: current_user %>
        </div>
        <p class="user-name text-center"><%= current_user.name %></p>
      </div>
  
      <div class="user-books col-12 col-lg-10">
        <h2 class="txt">Library</h2>
        <div class="book-box row" data-target="library.bookBox">
          <% if @books.count == 0 %>
            <div class="container purchase d-flex text-center">
              <p class="h2 mx-auto align-self-center">
                <%= link_to "Get some books", books_path%> <br>
                or <br>
                <%= link_to "Is there any book in your shopping cart",cart_path %>
              </p>
            </div>
          <% else %>
          <% @books.each do |book| %>
          <div class="book-item col-6 col-sm-4 col-md-3 d-flex flex-column justify-content-between">
            <div class="cover">
              <a class="cover-link" data-bookid="<%= book.id %>" href="#collapseBook" data-toggle="collapse" data-target="#collapseBook">
                <!-- 加入判斷避免該欄位使用假圖壞掉的 bug -->
                <%= render partial: "shared/frontend/book_cover", locals: {book: book, size: :small} %>
                <div class="x">
                  <%= render "shared/frontend/user_avatar", user: book.authors[0] %>
                </div>
              </a>
              <!-- 書本標題-->
              <div class="book-title text-center"><%= book.title %></div>
            </div>
  
            <!-- 線上閱讀 -->
            <div class="book-info">
              <!-- 加入判斷避免沒上傳檔案的書籍連結壞掉 -->
              <% if book.md_data %>
              <!-- 下載功能-->
                <p><%= link_to "下載", book.md_url, class:"uploadWholeBook", target: "_blank" %></p>
              <% else %>
                <%= link_to "Read on Simpub",read_book_path(book), class:"txt btn btn-primary w-100 mb-1" %>
                <div class="download btn btn-outline-secondary w-100" >Download</div> 
                <!-- production: 已上傳 PDF 才能允許上架 -->
              <% end %>
            </div>
          </div>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>   
  </section>
  
  <div class="library-info txt">
    <div class="collapse" id="collapseBook">
      <div class="card card-body mg-auto p-0 bg">
        <div class="info-group d-flex bg p-3">
  
          <div class="col-12 col-md-6 col-lg-6 d-flex row">
            <div class="cover d-flex flex-column px-4 col-md-12 col-lg-6">
              <!-- 書本封面 -->
              <div class="w-100 mb-4">
                <div class="info-cover-box"></div>
              </div>
              <!-- 完成度 -->
              <div class="completeness mt-auto">
                <div class="progress mx-auto mb-2"></div>
                <p class="text-center mb-0">This Book Is <span id="completeness"></span>% Complete</p>
                <p class="text-center mb-0">COMPLETED ON <span id="time"></span></p>
              </div>
            </div>
          <div class="info px-4 col-md-12 col-lg-6 d-flex flex-column">
          
          <!-- 標題與作者 -->
          <div class="book-info mb-3">
            <!-- 標題 -->
            <h1 class="title book-info-title"></h1>
            <!-- 作者 -->
            <div class="book-show-author d-flex align-items-center">
              <!-- 作者頭像 -->
              <div class="book-show-author-avatar book-info-avatar"></div>
              <!-- 作者名稱 -->
              <div class="book-show-author-name ml-2"></div>
            </div>
          </div>
  
          <!-- 評分 -->
          <div class="rating" role="optgroup">
            <% 1.upto(5) do |n| %>
              <i class="far fa-star fa-2x"></i>
            <% end %>
          </div>
  
          <!-- 關於此書 -->
          <div class="about mt-4">
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga enim vitae, consequuntur asperiores, itaque beatae maxime cumque sapiente quae eius odit, autem corrupti quos ipsa amet non iusto eveniet expedita?
            </p>
          </div>
        </div>
      </div>
  
      <div class="book-about col-12 col-md-6 col-lg-3 d-flex flex-column" >
        <div>
          <%= form_with model: @comment, url: "#", class: "comment-form" do |f| %>
            <div>
              <%= f.label :content, "Leave Comment Below：", class: "mb-2" %>
              <%= f.hidden_field :stars, id: "rating-input", min: "0", max: "5" %>
            </div>

            <div class="rating" role="optgroup">
              <% 1.upto(5) do |n| %>
                <i class="far fa-star fa-2x rating-star" id="rating-<%= n %>" data-rating="<%= n %>" tabindex="0" aria-label="Rate as one out of 5 stars" role="radio"></i>
              <% end %>
            </div>

            <div>
              <%= f.text_area :content, class: "d-block my-2 w-100" %>
            </div>

            <div>
              <%= f.submit "Send", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>