config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  # 測試用
  # devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  
  # 正式用
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks", confirmations: "users/confirmations" }
  # devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do
    get "/users", to: "users/registrations#new"
    get "/users/password", to: "users/passwords#new"
    get "/user_dashboard/settings", to: "users/registrations#edit", as: "user_dashboard"
  end

  namespace :users, path: :u do
    get "/:username", to: "profiles#show", as: "profile"
    post "/:username", to: "profiles#follow", as: "follow"
    get "/:username/wishlist", to: "profiles#wishlist", as: "wishlist"
    post "/:username/wishcart", to: "profiles#wishcart"
    delete "/:username/unwish", to: "profiles#unwish", as: "unwish"
  end
  
  namespace :users, path: :dash_board do
    get "/followship", to: "profiles#followship"
    get "/books", to: "authors#show"
    get "/library", to: "library#show"
    post "/library", to: "library#comment", as: "comment"
  end

  resources :books do
    member do
      get :editor_new
      post :editor_create
      get :editor_edit
      post :editor_update
      get :pricing
      patch :publish
      post :add_chapter
      post :add_section
      get :sample
      get :table_of_contents
      get :read
      patch :unpublish
      post :wish
    end
    
    collection do
      get :search
      post :get_content
      post :update_content
      post :rename
      post :delete_chapter_or_section
      post :all_content
      post :upload_pdf
      post :download_pdf
    end
  end

  get "/purchases", to: "users/purchase#index"
  get "/purchases_show", to: "users/purchase#show"

  resource :cart, only:[:show, :edit, :update, :destroy] do
    collection do
      post :add, path:'add/:id'
      get :payment
      post :checkout
      post :refund
      post :cartwish
    end
  end

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/cart.rb
class Cart
  SessionKey = :cart9527
  attr_reader :items

  def initialize(items = [])
    @items = items
  end
  
  def add_item(book_id, cart_price)
    @items << CartItem.new(book_id, cart_price)
  end

  def update_price(item, price)
    item.cart_price = price
  end

  def delete_item(items)
    @items = items
  end
  
  def empty? 
    @items.empty?
  end

  def total_price
    items.reduce(0) { |sum, item| sum + item.price }
  end

  def serialize
    all_items = items.map { |item|
      { "book_id" => item.book_id, "cart_price" => item.cart_price}
    }
    { "items" => all_items } 
  end

  def self.from_hash(hash)
    if hash.nil? 
      new []
    else
      new hash["items"].map { |item_hash| 
        @cart_item = CartItem.new(item_hash["book_id"], item_hash["cart_price"])
      }
    end
    # 1. 因為 Cart.from_hash 是類別方法，所以在定義方法的時候加上了 self.。
    # 2. 在 self.from_hash 方法中，不管傳進來的 Hash 是空的還是有資料，最終都是呼叫 new 方法產生一個 Cart 實體，並且把傳入的 Hash 的內容轉換成 CartItem 物件。
    # 3.  Cart 類別的 initialize 方法有做調整，讓它可以接收參數，並把參數指定給 @items 實體變數。
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :find_book, only: [:edit, :cartwish]

  def add
    cart_price = params[:cart_price][1..-1].to_f
    
    current_cart.add_item(params[:id], cart_price) 
    session[Cart::SessionKey] = current_cart.serialize
  end

  def show
    respond_to do |format|
      format.html
      format.json { current_cart }
    end
  end


  def edit
  end

  def cartwish
    if current_user
      current_user.wish_books << @book
      flash[:notice] = "Added item to your Wish List."
      render json: { redirect: cart_path }
    else
      flash[:notice] = "You need to sign in or sign up before continuing."
      render json: { redirect: new_user_session_path }
    end
  end

  def update
    index = params[:index].to_i
    price = params[:price][1..-1].to_f

    current_cart.update_price(current_cart.items[index], price)
    session[Cart::SessionKey] = current_cart.serialize

    redirect_to cart_path
  end

  def destroy
    cart = current_cart.items
    @items = cart.select.with_index { |item, index|
      item if index != params[:index].to_i
    }
    
    current_cart.delete_item(@items)
    session[Cart::SessionKey] = current_cart.serialize
  end


  def payment
    if current_cart.empty?
      redirect_to books_path, notice: "Nothing in the Cart"
    else
      if user_signed_in?
        if current_cart.total_price == 0
          create_order(current_user)
          current_cart.items.each do |item|
            current_user.bought_books << Book.find_by(id: item.book_id)
          end
                 
          session[Cart::SessionKey] = nil
          redirect_to root_path, notice: "Payment Success"
        end

        @token = gateway.client_token.generate
      else
        redirect_to new_user_session_path, notice: "You need to sign in or sign up before continuing."
      end
    end
  end

  def checkout
    if current_cart.total_price == 0
      create_order(current_user)
    else
      result = gateway.transaction.sale(
        amount: current_cart.total_price,
        payment_method_nonce: params[:nonce],
        options: {
          submit_for_settlement: true
        }
      )

      if result.success?
        # 成功付款建立訂單
        create_order(current_user, result.transaction.id)
      else
        redirect_to root_path, notice: "Error! Please try again"
      end
    end

    current_cart.items.each do |item|
      current_user.bought_books << Book.find_by(id: item.book_id)
    end
           
    session[Cart::SessionKey] = nil
    redirect_to root_path, notice: "Payment Success"
  end


  def refund
    order = current_user.orders.find_by(uuid: params[:uuid])
    if order.total == 0
      redirect_to purchases_path, notice: "This was a free purchase, so it cannot be refunded"
      return
    end

    transaction = gateway.transaction.find(params[:trans_id])

    if transaction.status == "settled" or transaction.status == "settling"
      refund = gateway.transaction.refund(transaction.id)
    elsif transaction.status == "submitted_for_settlement"
      refund = gateway.transaction.void(transaction.id)
    else
      redirect_to purchases_path, notice: "Refund error occurred, please contact customer service"
    end

    if refund.success?
      order.state = "refund"
      order.order_items.each do |item|
        BookUser.find_by(user_id: current_user, book_id: item.book).destroy
        current_user.bought_books.destroy(item.book)
      end
      order.destroy

      redirect_to purchases_path, notice: "Successfully requested a refund"
    else
      redirect_to purchases_path, notice: "Refund failed, please apply again"
    end
  end



  private
  def find_book
    @book = Book.find_by(id: params[:id])
  end

  def gateway
    Braintree::Gateway.new(
      environment: :sandbox, 
      merchant_id: ENV["merchant_id"],
      public_key: ENV["public_key"],
      private_key: ENV["private_key"],
    )
  end

  def create_order(user, id = nil)
    order = user.orders.create(
      payment_term: "credit card",
      state: "success",
      total: "#{current_cart.total_price}",
      transaction_id: id
    )
    
    # 建立訂單項目
    create_order_items(order)
  end

  def create_order_items(order)
    current_cart.items.each do |item|
      order.order_items.create(
        book_id: item.book_id,
        price: item.cart_price,
        amount: 1
      )
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    @cart ||= Cart.from_hash(session[Cart::SessionKey])
  end
end

app/views/carts/payment.html.erb
<section class="cart-payment txt container" data-controller="checkout">

  <div class="d-flex justify-content-center my-4">
    <h3 class="summary col-12 col-md-10 d-flex justify-content-start">Summary</h3>
  </div>

  <div class="checkoutstage_checkout d-flex justify-content-center">
    <table class="col-12 col-md-10 table table-borderless"> 
      <div>
        <thead class="mb-5">
          <tr class="confirm-details-title"> 
            <td class="">Product</td> 
            <td class="text-right">Quantity</td> 
            <td class="text-right">Subtotal</td>
          </tr>
        </thead>
      </div>
      <tbody class="confirm-details-item">
        <% current_cart.items.each do |item| %> 
          <tr class="">
            <td style="font-size:large" class="font-weight-bold">
              <%= item.book.title %>
            </td>
            <td class="text-right">
              1
            </td>
            <td class="text-right">
              $<%= sprintf("%.2f", item.price) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="check-out d-flex justify-content-center mt-3">
    <div class="col-12 col-md-10 d-flex justify-content-end" >
      <span class="mx-5">Total</span>
      $<%= sprintf("%.2f", current_cart.total_price) %>
    </div>
  </div>
  <hr class="border-bottom border-white col-10">
  <div class="d-flex justify-content-center ">
    <h3 class="col-10 d-flex justify-content-start">Credit Card Info</h3>
  </div>
  
  <%= form_with url: "/cart/checkout", method: "post", id: "payment_form", local: true do%>
    <div class="d-flex justify-content-center">
      <div id="dropin-container" data-token="<%= @token %>" class="col-12 col-md-10"></div>
      <input type="hidden" value="" id="nonce" name="nonce">
    </div>
    <div class="d-flex justify-content-center mt-2">
      <div class=" d-flex justify-content-end col-10">
        <button id="submit-button" class="btn-primary btn col-12 col-md-3" data-target="checkout.pay">Pay</button>
        <button class="ml-auto btn btn-secondary w-25 x" disabled data-target="checkout.wait">Please wait...</button>
      </div>
    </div>
  <% end %>
</section>

app/views/carts/show.html.erb
<section class="cart-show container mt-4" data-controller="cart">

  <div class="checkoutstage_review col-10 container d-flex justify-content-center ">
    <table id="cart-items" class="table">
      <thead class="txt d-none d-md-block">
        <tr class="row text-center">
          <th class="col-2">Product</th>
          <th class="col-6"></th>
          <th class="col-2">Quantity</th>
          <th class="col-2">Subtotal</th>
        </tr>
      </thead>

      <tbody>
        <% current_cart.items.each.with_index do |item, index| %>
          <tr class="row">
            <td class="col-12 col-md-2">
              <div style="font-size:large" class="font-weight-bold" >
                <%= link_to book_path(item.book), data: {target: "cart.cover"} do %>
                  <%= render partial: "shared/frontend/book_cover", locals: {book: item.book, size: :small} %>
                <% end %>
              </div>
            </td>
            <td class="col-12 col-md-6">
              <div style="font-size:large" class="font-weight-bold mb-2" >
                <%= link_to item.book.title, book_path(item.book), class:"product-title mx-1" %>
              </div>
              <div class="d-flex" data-index="<%= index %>" data-price="<%= item.price %>" data-bookid="<%= item.book.id %>">
                <button class="item-edit border-0 bg-transparent" data-target="cart.edit">Edit</button>
                <span class="mx-1">|</span>
                <button class="item-wishlist border-0 bg-transparent" data-target="cart.wish">Move to Wishlist</button>
                <span class="mx-1">|</span>
                <button class="item-delete border-0 bg-transparent" data-target="cart.delete">Delete</button>
              </div>
            </td>

            <td style="font-size: large" class="quantity txt col-12 col-md-2">
              1
            </td>
            <td style="font-size: large" class="subtotal txt col-12 col-md-2">
              $<%= sprintf("%.2f", item.price) %>
            </td>
          </tr>

        <% end %>
      </tbody>
    </table>
  </div>
    
  
  <div class="d-flex justify-content-center">
    <div class="col-10 d-flex justify-content-end align-items-center">Total</div>
  </div>

  <div class="check-out d-flex justify-content-center">
    <div class="cart-total col-10 d-flex justify-content-end align-items-center">
    	$<%= sprintf("%.2f", current_cart.total_price) %>
    </div>
  </div>

  
  <div class="d-flex justify-content-center my-5">
    <div class="col-10 d-flex justify-content-between">
      <%= link_to "Checkout", payment_cart_path, class: "ml-auto w-25 d-flex justify-content-center btn btn-primary", data: {target: "cart.payment"} %>
      <button class="ml-auto btn btn-secondary w-25 x" disabled data-target="cart.wait">Please wait...</button>
    </div>
  </div>
</section>